# Generated by Django 3.2.16 on 2022-10-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_alter_veiculo_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
