# Generated by Django 3.2.16 on 2022-10-05 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_alter_veiculo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
