# Generated by Django 3.2.16 on 2022-10-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0005_alter_veiculo_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
